FROM node:22-alpine AS builder

WORKDIR /app

# Install dependencies from root package.json
COPY package.json package-lock.json ./
RUN npm ci

# Copy all files and build
COPY . .
RUN npm run build

# Nginx block to serve frontend dist files
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 8001

CMD ["nginx", "-g", "daemon off;"]
